{% set name = "micro" %}
{% set version = "2.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/zyedidia/micro.git
  git_rev: v{{ version }}
  # url: https://github.com/zyedidia/micro/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: 40177579beb3846461036387b649c629395584a4bbe970f61ba7591bd9c0185a

build:
  number: 1

requirements:
  build:
    - {{ compiler('go-cgo') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - go-licenses
    - make

test:
  commands:
    - micro --version

about:
  home: https://micro-editor.github.io/
  license: MIT
  license_file:
    - LICENSE
    - LICENSE-THIRD-PARTY
  summary: 'A modern and intuitive terminal-based text editor'
  dev_url: https://github.com/zyedidia/micro

extra:
  recipe-maintainers:
    - dhirschfeld
